FROM node:10

MAINTAINER Ilkka Hauta-aho <ilkka.hauta-aho@miiliconsulting.com>

ARG API_ENDPOINT
WORKDIR /app

COPY . ./

RUN npm run build && \
    npm install -g serve

ENV API_URL $API_ENDPOINT
EXPOSE 5000

ENTRYPOINT API_URL=$API_URL npm start


