FROM ubuntu:16.04

MAINTAINER Ilkka Hauta-aho <ilkka.hauta-aho@miiliconsulting.com>

ENV DEBIAN_FRONTEND noninteractive

WORKDIR /app

COPY curler.sh .

RUN apt-get update && \
    apt-get install curl -y

CMD ["./curler.sh"]


