FROM node:10

MAINTAINER Ilkka Hauta-aho <ilkka.hauta-aho@miiliconsulting.com>

WORKDIR /app

COPY . ./

RUN npm run build && \
    npm install -g serve

EXPOSE 5000

CMD ["serve", "-s", "-l", "5000", "./dist"]


